version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    groups:
      gitsubmodule-all:
        patterns:
          - "*"