name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Install Node
      uses: actions/setup-node@v2

    - name: Cache Node Modules
      uses: actions/cache@v2
      id: cache-npm
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build Critical CSS
      run: npm run critical

    - name: Build Site
      run: npm run build