name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Cache Node Modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: node_modules
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build Critical CSS
        run: npm run critical

      - name: Build Site
        run: npm run build
