name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Critical CSS
        run: npm run critical

      - name: Build Site
        run: npm run build
