name: Check Links

on:
  schedule:
  - cron: 0 8 * * 1

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.1
      with:
        ref: gh-pages
        
    - name: Link Checker
      uses: peter-evans/link-checker@v1
      with:
        args: -v -r * -x ^.+linkedin.com.+$

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Link Checker Report
        content-filepath: ./link-checker/out.md
        labels: report, automated issue