name: Check Links

on:
  schedule:
  - cron: 0 8 * * 1

jobs:
  linkchecker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: true
        ref: gh-pages
    - name: Link Checker
      uses: peter-evans/link-checker@master
      with:
        args: -v -r *
    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_TITLE: Link Checker Report
        ISSUE_CONTENT_FILEPATH: ./link-checker/out.md
        ISSUE_LABELS: report, automated issue