name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Install Node
      uses: actions/setup-node@master
    - name: Install dependencies
      run: npm install
    - name: Build Critical CSS
      run: npm run critical
    - name: Build Site
      run: npm run build
    - name: Deploy Site
      uses: peaceiris/actions-gh-pages@master
      if: success()
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    - name: Purge Cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    - name: Load Site
      run: curl ${{ GITHUB_REPOSITORY }} -L