name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
    - name: Cache Node Modules
      uses: actions/cache@v1
      id: cache-npm
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package.json') }}
    - name: Install dependencies
      run: npm install
    - name: Build Critical CSS
      run: npm run critical
    - name: Build Site
      run: npm run build
    - name: Deploy Site
      uses: peaceiris/actions-gh-pages@v3.6.1
      if: success()
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    - name: Purge Cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    - name: Load Site
      run: curl $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2-) --location --output /dev/null